/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package homework20;

/**
 *
 * @author Mike
 */
public class Startup extends javax.swing.JFrame {

    /**
     * Creates new form Startup
     */
    public Startup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFarenheitInput = new javax.swing.JTextField();
        lblFarenheitInput = new javax.swing.JLabel();
        btnConvertFarenheit = new javax.swing.JButton();
        lblCelciusOutput = new javax.swing.JLabel();
        txtCelciusOutput = new javax.swing.JTextField();
        txtCelciusInput = new javax.swing.JTextField();
        lblCelciusInput = new javax.swing.JLabel();
        btnConvertCelcius = new javax.swing.JButton();
        lblFarenheitOutput = new javax.swing.JLabel();
        txtFarenheitOutput = new javax.swing.JTextField();
        lblConvertFarienheit = new javax.swing.JLabel();
        lblConvertCelcius = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Temperature Converter");

        txtFarenheitInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFarenheitInputActionPerformed(evt);
            }
        });

        lblFarenheitInput.setText("Input Farenheit");

        btnConvertFarenheit.setText("Convert");
        btnConvertFarenheit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConvertFarenheitMouseClicked(evt);
            }
        });
        btnConvertFarenheit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertFarenheitActionPerformed(evt);
            }
        });

        lblCelciusOutput.setText("Celcius Result");

        txtCelciusOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelciusOutputActionPerformed(evt);
            }
        });

        txtCelciusInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelciusInputActionPerformed(evt);
            }
        });

        lblCelciusInput.setText("Input Celcius");

        btnConvertCelcius.setText("Convert");
        btnConvertCelcius.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnConvertCelciusMouseClicked(evt);
            }
        });
        btnConvertCelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertCelciusActionPerformed(evt);
            }
        });

        lblFarenheitOutput.setText("Farenheit Result");

        txtFarenheitOutput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFarenheitOutputActionPerformed(evt);
            }
        });

        lblConvertFarienheit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConvertFarienheit.setText("Convert Farienheit to Celcius");

        lblConvertCelcius.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblConvertCelcius.setText("Convert Celcius to Farenheit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFarenheitInput)
                            .addComponent(lblCelciusOutput))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtFarenheitInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnConvertFarenheit))
                            .addComponent(txtCelciusOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblConvertFarienheit, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCelciusInput)
                                    .addComponent(lblFarenheitOutput))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCelciusInput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnConvertCelcius))
                                    .addComponent(txtFarenheitOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblConvertCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblConvertFarienheit, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFarenheitInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFarenheitInput)
                    .addComponent(btnConvertFarenheit))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelciusOutput)
                    .addComponent(txtCelciusOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblConvertCelcius, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelciusInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCelciusInput)
                    .addComponent(btnConvertCelcius))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFarenheitOutput)
                    .addComponent(txtFarenheitOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFarenheitInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFarenheitInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFarenheitInputActionPerformed

    private void btnConvertFarenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertFarenheitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertFarenheitActionPerformed

    private void txtCelciusOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelciusOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelciusOutputActionPerformed

    private void btnConvertFarenheitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertFarenheitMouseClicked
        txtCelciusOutput.setText(new TemperatureConverterService().ConvertToCelcius(txtFarenheitInput.getText()));
    }//GEN-LAST:event_btnConvertFarenheitMouseClicked

    private void txtCelciusInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelciusInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCelciusInputActionPerformed

    private void btnConvertCelciusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnConvertCelciusMouseClicked
        txtFarenheitOutput.setText(new TemperatureConverterService().ConvertToFarenheit(txtCelciusInput.getText()));
    }//GEN-LAST:event_btnConvertCelciusMouseClicked

    private void btnConvertCelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertCelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConvertCelciusActionPerformed

    private void txtFarenheitOutputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFarenheitOutputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFarenheitOutputActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Startup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Startup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertCelcius;
    private javax.swing.JButton btnConvertFarenheit;
    private javax.swing.JLabel lblCelciusInput;
    private javax.swing.JLabel lblCelciusOutput;
    private javax.swing.JLabel lblConvertCelcius;
    private javax.swing.JLabel lblConvertFarienheit;
    private javax.swing.JLabel lblFarenheitInput;
    private javax.swing.JLabel lblFarenheitOutput;
    private javax.swing.JTextField txtCelciusInput;
    private javax.swing.JTextField txtCelciusOutput;
    private javax.swing.JTextField txtFarenheitInput;
    private javax.swing.JTextField txtFarenheitOutput;
    // End of variables declaration//GEN-END:variables
}
